model_name: "TitleQuill"
model_type: "google/flan-t5-small"

strategy: "divided_tasks" # One of "combined_tasks", "combined_tasks_shuffle", "divided_tasks", "divided_tasks_ce_eisl"
lambda_: 1.0 # Used only in "divided_tasks_ce_eisl" strategy
train_batch_size: 16
val_batch_size: 32
max_epochs: 5
max_length: 512
max_new_tokens: 150
num_workers: 0
debug_run: False
lr: 0.001