defaults:
  - _self_
  - data: oagkx
  - hydra: default
  # For disable logging, set to null
  - logger: null #wandb
  - model: null

device: "cpu" #"cuda:0"
log_interval: 100
metrics_title: ["rouge", "bleu", "meteor"]
metrics_keywords: ["f1", "precision", "recall"]
seed: 123
output_dir: "output"